### ISSUE TITLE
Cannot find http://localhost:4502/etc/map.-1.json

### ISSUE THREAD

**Issue by AliShirazi** [Cognifide/Carty#3]
Hi guys,

Great project! This mapping/sling resolution is a pain and this tool definitely has me excited in making the process easier. I followed the instructions, but unfortunately have this error when I load up carty:  404 error, cannot find"http://localhost:4502/etc/map.-1.json".  I have installed carty and reinstalled via the package manager, but no luck.

Any ideas?

**Comment by henrykuijpers** [comment]
Does the /etc/map node actually exist?

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
